### ISSUE TITLE
cloud-example.js APIs

### ISSUE THREAD

**Issue by hwilyric** [SamsungARTIK/artik-sdk#18]
I think it doesn’t have APIs related with getting actions and messages
Thanks

**Comment by glemercier** [comment]
If you are referring to "actions" and "messages" from ARTIK Cloud, then there are several ways for your device to connect to ARTIK Cloud and exchange message/actions:

- REST (send messages only): API [here](https://github.com/SamsungARTIK/artik-sdk/blob/master/doc/CLOUD_README.md#send_message)
- Websocket: example [here](https://github.com/SamsungARTIK/artik-sdk/blob/master/examples/cloud-websocket-example.js) 
- MQTT: example [here](https://github.com/SamsungARTIK/artik-sdk/blob/master/examples/mqtt-example.js)

**Comment by hwilyric** [comment]
I thought REST API also has POST method like http-example.js
Is ther any specific reason that REST API are only available sending msgs and actions?
since I'm trying to make an example that getting actions from cloud or other device using REST API.

**Comment by glemercier** [comment]
REST APIs have no direct way to receive actions by design choice. REST calls are always made on the initiative of the client device. In case of an action triggered to this device, the server needs a way to reach out to the device, which may not maintain a HTTP connection to the cloud.

Therefore the choice has been made to use another more appropriate protocol for the devices to be notified of an action form the cloud, websocket was the first obvious one.
