### ISSUE TITLE
websocket doesn't shutdown after server disconnects 

### ISSUE THREAD

**Issue by viktorgino** [SamsungARTIK/artik-sdk#24]
Hi

On an Artik 053 board when the websocket server disconnects without sending a close message the websocket connection is still considered open. If trying to close this socket connection after the server disconnected it stalls when calling websocket_queue_close(), because it tries to send a close message until it fails or it succeeds. 

The websocket client doesn't shutdown, because here: [tinyara_websocket.c#L121](https://github.com/SamsungARTIK/artik-sdk/blob/1.7-maintenance/src/modules/connectivity/websocket/tinyara_websocket.c#L121) not all errors are considered. In my case [this](https://github.com/SamsungARTIK/artik-sdk/blob/1.7-maintenance/src/modules/connectivity/websocket/tinyara_websocket.c#L163) returns : `ENOTCONN - Transport endpoint is not connected`. Is there a need to check for specific error codes or could that be completely removed?

Thanks for your help in advance.

**Comment by glemercier** [comment]
Thanks for reporting, it looks like we don't check errno properly.
Please try the patch from this PR: https://github.com/SamsungARTIK/artik-sdk/pull/25
And let us know if it fixes your issue, in the meantime we'll be conducting our own testing.

Note that you'll have to update the "external/artik-sdk" submodule in TizenRT to point to the new commit, then commit this change in the TizenRT repo (even locally) before you run 'make'. This is because 'make' does a 'git submodule update' every time it runs, and will overcome any non-commited changed on the "external/artik-sdk" revision.

**Comment by viktorgino** [comment]
Thanks for the quick answer.

I've already tested a very similar solution, but rather than a using switch just added ENOTCONN to the if statement, and that works for me. My question is whether it'd be worth checking for other socket related error codes?

**Comment by glemercier** [comment]
I modified the patch to handle all errors this way:

- EAGAIN, EBUSY, try again a few times before exiting on error
- All others, exiting on error

The switch/case will be more convenient if we later want to handle specific errors in a special way. The patch has been merged and available here: https://github.com/SamsungARTIK/artik-sdk/commit/cb7f1544ab72ec41e167e1913fce1ecc36053681

Feel free to let us know if you still have some issues in this area.
