### ISSUE TITLE
Access to 530s security controller and element.

### ISSUE THREAD

**Issue by cerealkill** [SamsungARTIK/artik-sdk#27]
Hi, I am developing an ethereum based solution on top of the Artik530s and trying to access it's secure sub system. I am wondering if I could use it to:

ECDSA -> Elliptic Curve secp256k1
http://www.secg.org/sec2-v2.pdf

KECCAK 256 HASHING -> based on XOR and ROT and also labeled as SHA3-256 but sometimes they differ in result depending on implementation.
https://keccak.team/keccak_specs_summary.html

I did not find many examples nor docs like the chip's datasheets. The downloadable docs don't mention compatibility to the (s) family.

Could you please help me?

**Comment by glemercier** [comment]
You may use the security APIs documented here: https://developer.artik.io/documentation/security-api/see__authentication_8h.html

However KEKKAK hashing is not supported by the Secure Element, only the following algos are at the moment: HASH_MD5, HASH_SHA1, HASH_SHA224, HASH_SHA256, HASH_SHA384, HASH_SHA512.

ECDSA signature with secp256k1 is not supported either: https://developer.artik.io/documentation/security-api/group__see__authentication.html#ga5fc4196d008f675a8b0e7a33cd827040

Closest match is secp256r1.

Also note that the Secure Element is mainly used to benefit from its hardware root of trust, whose main purpose is to keep the private keys as secure as possible baked into the Secure Element. On the other hand, you should not expect better performance for signature or hashing when using the Secure Element rather than using plain software libraries, since there is additional communication needed between the main CPU and the Secure Element to exchange data. To summarize: the SE should be used for its enhanced security feature, not for its performance.

Hope it's clearer for you now.

**Comment by cerealkill** [comment]
That helped a lot, thanks.

The whole point was not performance but securing the user's private key. The hashing algo I could replace yes but the most important part is ECDSA signing that cannot be done with a different curve.

Could I run computations on any of the secure chips? In a way that the pk is stored on the safe storage and never touching the main processor memory?

**Comment by cerealkill** [comment]
Any updates?

**Comment by cerealkill** [comment]
Thank you for the support.
