### ISSUE TITLE
1.9.0 fails to build

### ISSUE THREAD

**Issue by bswhite1** [SamsungARTIK/artik-sdk#37]
1.9.0 and master are failing to build. They both failing to find "libcoap-1". libcoap is installed and is the newest version. I could not find a reference anywhere online to download "libcoap-1"

I installed a clean image of A533s_os_18.10.00 since it also wasn't building with A533s_os_18.05.00

I install the following packages:
debhelper 
git 
cmake 
build-essential 
libwebsockets-dev 
libglib2.0-dev 
libgstreamer1.0-dev 
libdbus-1-dev 
libcurl4-openssl-dev 
libssl-dev 
libmosquitto-dev 
libcunit1-dev 
libzigbee-dev 
wakaama-client-dev 
libcoap

**Comment by glemercier** [comment]
You need to install the `libcoap-dev` package since you need the headers of the libcoap library. Also please refer to the following for the full list of packages to install:

`apt install cmake build-essential libwebsockets-dev libglib2.0-dev libgstreamer1.0-dev libdbus-1-dev libcurl4-openssl-dev libssl-dev libmosquitto-dev libcunit1-dev libzigbee-dev wakaama-client-dev`

**Comment by bswhite1** [comment]
Yup, that fixed it. Thanks!
